name: Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:

    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt install libgtk-3-dev

    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
        cache: "pip"
        cache-dependency-path: "pyproject.toml"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install '.[test]'
    - name: Lint with mypy
      run: |
        mypy .
    - name: Lint with ruff
      run: |
        ruff check .
    - name: Check formatting with ruff
      run: |
        ruff format --check .
    - name: Create exectuable
      run: |
        make compile
    - name: Archive executable
      uses: actions/upload-artifact@v4
      with:
        name: executable_${{ runner.os }}
        path: dist/dqmj1_randomizer/*